// Code generated by "stringer -type=LineBreakingClass"; DO NOT EDIT.

package unicode

import "strconv"

const _LineBreakingClass_name = "CMClassBAClassLFClassBKClassCRClassNLClassSPClassEXClassQUClassALClassPRClassPOClassOPClassCPClassISClassHYClassSYClassNUClassAIClassBBClassGLClassSAClassJTClassJVClassJLClassNSClassZWClassZWJClassWJClassCLClassIDClassCJClassH2ClassH3ClassEBClassEMClassHLClassRIClassXXClassanyClasssoteot"

var _LineBreakingClass_index = [...]uint16{0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98, 105, 112, 119, 126, 133, 140, 147, 154, 161, 168, 175, 182, 189, 197, 204, 211, 218, 225, 232, 239, 246, 253, 260, 267, 274, 282, 285, 288}

func (i LineBreakingClass) String() string {
	if i < 0 || i >= LineBreakingClass(len(_LineBreakingClass_index)-1) {
		return "LineBreakingClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LineBreakingClass_name[_LineBreakingClass_index[i]:_LineBreakingClass_index[i+1]]
}
