// Code generated by "stringer -type=TypesettingParameter"; DO NOT EDIT.

package parameters

import "strconv"

const _TypesettingParameter_name = "noneP_LANGUAGEP_SCRIPTP_TEXTDIRECTIONP_BASELINESKIPP_LINESKIPP_LINESKIPLIMITP_HYPHENPENALTYP_STOPPER"

var _TypesettingParameter_index = [...]uint8{0, 4, 14, 22, 37, 51, 61, 76, 91, 100}

func (i TypesettingParameter) String() string {
	if i < 0 || i >= TypesettingParameter(len(_TypesettingParameter_index)-1) {
		return "TypesettingParameter(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypesettingParameter_name[_TypesettingParameter_index[i]:_TypesettingParameter_index[i+1]]
}
