// Code generated by "stringer -type=DisplayMode"; DO NOT EDIT.

package layout

import "strconv"

const (
	_DisplayMode_name_0 = "NoModeDisplayNoneFlowMode"
	_DisplayMode_name_1 = "BlockMode"
	_DisplayMode_name_2 = "InlineMode"
	_DisplayMode_name_3 = "ListItemMode"
	_DisplayMode_name_4 = "FlowRoot"
	_DisplayMode_name_5 = "FlexMode"
	_DisplayMode_name_6 = "GridMode"
	_DisplayMode_name_7 = "TableMode"
	_DisplayMode_name_8 = "ContentsMode"
)

var (
	_DisplayMode_index_0 = [...]uint8{0, 6, 17, 25}
)

func (i DisplayMode) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _DisplayMode_name_0[_DisplayMode_index_0[i]:_DisplayMode_index_0[i+1]]
	case i == 4:
		return _DisplayMode_name_1
	case i == 8:
		return _DisplayMode_name_2
	case i == 16:
		return _DisplayMode_name_3
	case i == 32:
		return _DisplayMode_name_4
	case i == 64:
		return _DisplayMode_name_5
	case i == 128:
		return _DisplayMode_name_6
	case i == 256:
		return _DisplayMode_name_7
	case i == 512:
		return _DisplayMode_name_8
	default:
		return "DisplayMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
